INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped01", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped02", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped03", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped04", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped05", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped06", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped07", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped08", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped09", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped10", "01", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped11", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped12", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped13", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped14", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped15", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped16", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped17", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped18", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped19", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("ped20", "02", "Pediatría", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin01", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin02", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin03", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin04", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin05", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin06", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin07", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin08", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin09", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin10", "01", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin11", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin12", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin13", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin14", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin15", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin16", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin17", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin18", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin19", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("gin20", "02", "Ginecología", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min01", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min02", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min03", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min04", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min05", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min06", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min07", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min08", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min09", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min10", "01", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min11", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min12", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min13", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min14", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min15", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min16", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min17", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min18", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min19", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("min20", "02", "Medicina interna", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg01", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg02", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg03", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg04", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg05", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg06", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg07", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg08", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg09", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg10", "03", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg11", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg12", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg13", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg14", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg15", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg16", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg17", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg18", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg19", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg20", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg21", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg22", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg23", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg24", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg25", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg26", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg27", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg28", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg29", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("urg30", "04", "Urgencias", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir01", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir02", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir03", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir04", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir05", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir06", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir07", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir08", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir09", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir10", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir11", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir12", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir13", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir14", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir15", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir16", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir17", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir18", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir19", "05", "Cirugía", "adm001");
INSERT IGNORE INTO HABITACION (HABITACION_ID, HABITACION_PISO, HABITACION_AREA, ADMINISTRADOR_ID)
VALUES ("cir20", "05", "Cirugía", "adm001");

INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno1", "06", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno2", "06", "doc1", "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno3", "06", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno4", "06", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno5", "06", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno6", "07", "doc2", "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno7", "07", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno8", "07", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno9", "07", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno10", "07", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno11", "08", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno12", "08", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno13", "08", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno14", "08", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno15", "08", NULL, "adm001");
INSERT IGNORE INTO CONSULTORIO (CONSULTORIO_ID, CONSULTORIO_PISO, DOCTOR_ID, ADMINISTRADOR_ID)
VALUES ("cno16", "01", NULL, "adm001");
