CREATE TABLE IF NOT EXISTS ADMINISTRADOR
(
    ADMINISTRADOR_ID VARCHAR(12) NOT NULL PRIMARY KEY, -- primary key column
    ADMINISTRADOR_NOMBRES VARCHAR(50) NOT NULL,
    ADMINISTRADOR_APELLIDOS VARCHAR(50) NOT NULL,
    ADMINISTRADOR_PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE
(
    PACIENTE_ID VARCHAR(12) NOT NULL PRIMARY KEY, -- primary key column
    PACIENTE_NOMBRES VARCHAR(50) NOT NULL,
    PACIENTE_APELLIDOS VARCHAR(50) NOT NULL,
    PACIENTE_FECHANACIMIENTO DATE NOT NULL,
    PACIENTE_SEXO CHAR(1) NOT NULL,
    PACIENTE_LUGARNACIMIENTO VARCHAR(100) NOT NULL,
    PACIENTE_CURP VARCHAR(100) NOT NULL,
    PACIENTE_GRUPOSANGUINEO VARCHAR(5) NOT NULL,
    PACIENTE_ENFERMEDADESPREEXISTENTES VARCHAR(200),
    PACIENTE_ALERGIAS VARCHAR(200),
    PACIENTE_EMAIL VARCHAR(50),
    PACIENTE_TELEFONO VARCHAR(12) NOT NULL,
    PACIENTE_DIRECCION VARCHAR(200) NOT NULL,
    PACIENTE_CONTACTO_NOMBRE VARCHAR(50) NOT NULL,
    PACIENTE_CONTACTO_TELEFONO VARCHAR(12) NOT NULL,
    PACIENTE_CONTACTO_EMAIL VARCHAR(12),
    PACIENTE_CONTACTO_DIRECCION VARCHAR(100) NOT NULL,
    ADMINISTRADOR_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTEINTERNADO
(
    PACIENTEINTERNADO_ID VARCHAR(12) NOT NULL PRIMARY KEY, -- primary key column
    PACIENTEINTERNADO_FECHAINGRESO DATETIME NOT NULL,
    PACIENTEINTERNADO_FECHAALTA DATETIME,
    PACIENTEINTERNADO_OBSERVACION VARCHAR(2000) NOT NULL,
    PACIENTE_ID VARCHAR(12) NOT NULL,
    HABITACION_ID VARCHAR(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTETRANSITORIO 
(
    PACIENTETRANSITORIO_ID VARCHAR(12) NOT NULL PRIMARY KEY, -- primary key column
    PACIENTE_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS DOCTOR
(
    DOCTOR_ID VARCHAR(12) NOT NULL PRIMARY KEY, -- primary key column
    DOCTOR_PASSWORD VARCHAR(100) NOT NULL,
    DOCTOR_NOMBRES VARCHAR(50) NOT NULL,
    DOCTOR_APELLIDOS VARCHAR(50) NOT NULL,
    ADMINISTRADOR_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENFERMERO
(
    ENFERMERO_ID VARCHAR(12) NOT NULL PRIMARY KEY, -- primary key column
    ENFERMERO_PASSWORD VARCHAR(100) NOT NULL,
    ENFERMERO_NOMBRES VARCHAR(50) NOT NULL,
    ENFERMERO_APELLIDOS VARCHAR(50) NOT NULL,
    ADMINISTRADOR_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS LABORATORISTA
(
    LABORATORISTA_ID VARCHAR(12) NOT NULL PRIMARY KEY, -- primary key column
    LABORATORISTA_PASSWORD VARCHAR(100) NOT NULL,
    LABORATORISTA_NOMBRES VARCHAR(50) NOT NULL,
    LABORATORISTA_APELLIDOS VARCHAR(50) NOT NULL,
    ADMINISTRADOR_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA
(
    CONSULTA_ID VARCHAR(12) NOT NULL PRIMARY KEY, -- primary key column
    CONSULTA_FECHA DATETIME NOT NULL,
    CONSULTA_OBSERVACIONES VARCHAR(200),
    CONSULTA_COMENTARIO VARCHAR(500),
    DOCTOR_ID VARCHAR(12) NOT NULL,
    PACIENTETRANSITORIO_ID VARCHAR(12) NOT NULL,
    CONSULTORIO_ID VARCHAR(8) NOT NULL
);

CREATE TABLE IF NOT EXISTS EXAMEN
(
    EXAMEN_ID VARCHAR(12) NOT NULL PRIMARY KEY, -- primary key column
    EXAMEN_DIAGNOSTICO VARCHAR(10000) NOT NULL,
    EXAMEN_FECHA DATETIME NOT NULL,
    EXAMEN_MUESTRA VARCHAR(50),
    PACIENTE_ID VARCHAR(12) NOT NULL,
    DOCTOR_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESULTADO
(
    RESULTADO_ID VARCHAR(12) NOT NULL PRIMARY KEY,
    RESULTADO_DIAGNOSTICO VARCHAR(10000) NOT NULL,
    RESULTADO_TEXTO VARCHAR(2000) NOT NULL,
    RESULTADO_FECHA DATETIME NOT NULL,
    EXAMEN_ID VARCHAR(12) NOT NULL,
    PACIENTE_ID VARCHAR(12) NOT NULL,
    LABORATORISTA_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMENTARIO
(
    COMENTARIO_ID VARCHAR(12) NOT NULL PRIMARY KEY,
    COMENTARIO_TEXTO VARCHAR(200) NOT NULL,
    COMENTARIO_FECHA DATETIME NOT NULL,
    RESULTADO_ID VARCHAR(12) NOT NULL,
    DOCTOR_ID VARCHAR(12),
    LABORATORISTA_ID VARCHAR(12)
);

CREATE TABLE IF NOT EXISTS TURNO_ENFERMERO
(
    TURNO_ENFERMERO_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TURNO_HORARIO VARCHAR(10) NOT NULL,  -- Matutino, vespertino, nocturno
    HABITACION_ID VARCHAR(6) NOT NULL,
    ADMINISTRADOR_ID VARCHAR(12) NOT NULL,
    ENFERMERO_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS TURNO_DOCTOR
(
    TURNO_DOCTOR_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TURNO_HORARIO VARCHAR(10) NOT NULL,  -- Matutino, vespertino, nocturno
    HABITACION_ID VARCHAR(6) NOT NULL,
    ADMINISTRADOR_ID VARCHAR(12) NOT NULL,
    DOCTOR_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS HABITACION
(
    HABITACION_ID VARCHAR(18) NOT NULL PRIMARY KEY,
    HABITACION_PISO VARCHAR(4) NOT NULL,
    HABITACION_AREA VARCHAR(50) NOT NULL,
    ADMINISTRADOR_ID VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTORIO
(
    CONSULTORIO_ID VARCHAR(6) NOT NULL PRIMARY KEY,
    CONSULTORIO_PISO VARCHAR(4) NOT NULL,
    DOCTOR_ID VARCHAR(12),
    ADMINISTRADOR_ID VARCHAR(12) NOT NULL
);

ALTER TABLE PACIENTE
ADD FOREIGN KEY (ADMINISTRADOR_ID) REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID);
ALTER TABLE DOCTOR
ADD FOREIGN KEY (ADMINISTRADOR_ID) REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID);
ALTER TABLE CONSULTORIO
ADD FOREIGN KEY (ADMINISTRADOR_ID) REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID);
ALTER TABLE ENFERMERO
ADD FOREIGN KEY (ADMINISTRADOR_ID) REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID);
ALTER TABLE LABORATORISTA
ADD FOREIGN KEY (ADMINISTRADOR_ID) REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID);
ALTER TABLE HABITACION
ADD FOREIGN KEY (ADMINISTRADOR_ID) REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID);

ALTER TABLE PACIENTETRANSITORIO
ADD FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID);
ALTER TABLE PACIENTEINTERNADO
ADD FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID);
ALTER TABLE PACIENTEINTERNADO
ADD FOREIGN KEY (HABITACION_ID) REFERENCES HABITACION(HABITACION_ID);

ALTER TABLE CONSULTA
ADD FOREIGN KEY (PACIENTETRANSITORIO_ID) REFERENCES PACIENTETRANSITORIO(PACIENTETRANSITORIO_ID);
ALTER TABLE CONSULTA
ADD FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID);
ALTER TABLE CONSULTA
ADD FOREIGN KEY (CONSULTORIO_ID) REFERENCES CONSULTORIO(CONSULTORIO_ID);

ALTER TABLE EXAMEN
ADD FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID);
ALTER TABLE EXAMEN
ADD FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID);

ALTER TABLE RESULTADO
ADD FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID);
ALTER TABLE RESULTADO
ADD FOREIGN KEY (EXAMEN_ID) REFERENCES EXAMEN(EXAMEN_ID);
ALTER TABLE RESULTADO
ADD FOREIGN KEY (LABORATORISTA_ID) REFERENCES LABORATORISTA(LABORATORISTA_ID);

ALTER TABLE COMENTARIO
ADD FOREIGN KEY (RESULTADO_ID) REFERENCES RESULTADO(RESULTADO_ID);
ALTER TABLE COMENTARIO
ADD FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID);
ALTER TABLE COMENTARIO
ADD FOREIGN KEY (LABORATORISTA_ID) REFERENCES LABORATORISTA(LABORATORISTA_ID);

ALTER TABLE TURNO_DOCTOR
ADD FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID);
ALTER TABLE TURNO_DOCTOR
ADD FOREIGN KEY (HABITACION_ID) REFERENCES HABITACION(HABITACION_ID);
ALTER TABLE TURNO_DOCTOR
ADD FOREIGN KEY (ADMINISTRADOR_ID) REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID);

ALTER TABLE TURNO_ENFERMERO
ADD FOREIGN KEY (ENFERMERO_ID) REFERENCES ENFERMERO(ENFERMERO_ID);
ALTER TABLE TURNO_ENFERMERO
ADD FOREIGN KEY (HABITACION_ID) REFERENCES HABITACION(HABITACION_ID);
ALTER TABLE TURNO_ENFERMERO
ADD FOREIGN KEY (ADMINISTRADOR_ID) REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID);

ALTER TABLE CONSULTORIO
ADD FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID);

